/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QPlainTextEdit *readPlainTextEdit;
    QTextEdit *writeTextEdit;
    QPushButton *chartPushButton;
    QPushButton *actionConfigure;
    QPushButton *actionConnect;
    QPushButton *actionDisconnect;
    QPushButton *actionSend;
    QPushButton *actionClear;
    QWidget *tab_2;
    QWidget *horizontalLayoutWidget;
    QHBoxLayout *mainHorLayout;
    QRadioButton *ValidRadioButton;
    QPushButton *stopBtn;
    QCheckBox *YcheckBox;
    QLabel *paramLabel;
    QCheckBox *XcheckBox;
    QLineEdit *paramLineEdit;
    QCheckBox *autoCheckBox;
    QWidget *tab_3;
    QSlider *verticalSlider;
    QSlider *verticalSlider_2;
    QSlider *verticalSlider_3;
    QSlider *verticalSlider_4;
    QSlider *verticalSlider_5;
    QSlider *verticalSlider_6;
    QSlider *verticalSlider_7;
    QSlider *verticalSlider_15;
    QSlider *verticalSlider_16;
    QSlider *verticalSlider_17;
    QSlider *verticalSlider_18;
    QSlider *verticalSlider_19;
    QSlider *verticalSlider_20;
    QSlider *verticalSlider_21;
    QSlider *verticalSlider_22;
    QSlider *verticalSlider_23;
    QSlider *verticalSlider_24;
    QSlider *verticalSlider_25;
    QSlider *verticalSlider_26;
    QSlider *verticalSlider_27;
    QSlider *verticalSlider_28;
    QSlider *verticalSlider_29;
    QSlider *verticalSlider_30;
    QSlider *verticalSlider_31;
    QSlider *verticalSlider_32;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QGroupBox *groupBox;
    QPushButton *pushButton;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QLabel *statusBar;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1060, 545);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 1031, 471));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        readPlainTextEdit = new QPlainTextEdit(tab);
        readPlainTextEdit->setObjectName(QStringLiteral("readPlainTextEdit"));
        readPlainTextEdit->setGeometry(QRect(0, 0, 331, 151));
        readPlainTextEdit->setFrameShadow(QFrame::Plain);
        writeTextEdit = new QTextEdit(tab);
        writeTextEdit->setObjectName(QStringLiteral("writeTextEdit"));
        writeTextEdit->setGeometry(QRect(0, 160, 331, 70));
        chartPushButton = new QPushButton(tab);
        chartPushButton->setObjectName(QStringLiteral("chartPushButton"));
        chartPushButton->setGeometry(QRect(190, 290, 80, 20));
        actionConfigure = new QPushButton(tab);
        actionConfigure->setObjectName(QStringLiteral("actionConfigure"));
        actionConfigure->setGeometry(QRect(100, 290, 80, 20));
        actionConnect = new QPushButton(tab);
        actionConnect->setObjectName(QStringLiteral("actionConnect"));
        actionConnect->setGeometry(QRect(10, 260, 80, 20));
        actionDisconnect = new QPushButton(tab);
        actionDisconnect->setObjectName(QStringLiteral("actionDisconnect"));
        actionDisconnect->setGeometry(QRect(10, 290, 80, 20));
        actionSend = new QPushButton(tab);
        actionSend->setObjectName(QStringLiteral("actionSend"));
        actionSend->setGeometry(QRect(190, 260, 80, 20));
        actionClear = new QPushButton(tab);
        actionClear->setObjectName(QStringLiteral("actionClear"));
        actionClear->setGeometry(QRect(100, 260, 80, 20));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        horizontalLayoutWidget = new QWidget(tab_2);
        horizontalLayoutWidget->setObjectName(QStringLiteral("horizontalLayoutWidget"));
        horizontalLayoutWidget->setGeometry(QRect(0, 0, 1031, 321));
        mainHorLayout = new QHBoxLayout(horizontalLayoutWidget);
        mainHorLayout->setObjectName(QStringLiteral("mainHorLayout"));
        mainHorLayout->setContentsMargins(0, 0, 0, 0);
        ValidRadioButton = new QRadioButton(tab_2);
        ValidRadioButton->setObjectName(QStringLiteral("ValidRadioButton"));
        ValidRadioButton->setGeometry(QRect(230, 370, 91, 18));
        stopBtn = new QPushButton(tab_2);
        stopBtn->setObjectName(QStringLiteral("stopBtn"));
        stopBtn->setGeometry(QRect(230, 340, 80, 20));
        YcheckBox = new QCheckBox(tab_2);
        YcheckBox->setObjectName(QStringLiteral("YcheckBox"));
        YcheckBox->setGeometry(QRect(130, 340, 73, 18));
        paramLabel = new QLabel(tab_2);
        paramLabel->setObjectName(QStringLiteral("paramLabel"));
        paramLabel->setGeometry(QRect(80, 370, 31, 21));
        XcheckBox = new QCheckBox(tab_2);
        XcheckBox->setObjectName(QStringLiteral("XcheckBox"));
        XcheckBox->setGeometry(QRect(80, 340, 73, 18));
        paramLineEdit = new QLineEdit(tab_2);
        paramLineEdit->setObjectName(QStringLiteral("paramLineEdit"));
        paramLineEdit->setGeometry(QRect(110, 370, 113, 20));
        autoCheckBox = new QCheckBox(tab_2);
        autoCheckBox->setObjectName(QStringLiteral("autoCheckBox"));
        autoCheckBox->setGeometry(QRect(180, 340, 73, 18));
        autoCheckBox->setChecked(true);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        verticalSlider = new QSlider(tab_3);
        verticalSlider->setObjectName(QStringLiteral("verticalSlider"));
        verticalSlider->setGeometry(QRect(20, 20, 31, 160));
        verticalSlider->setOrientation(Qt::Vertical);
        verticalSlider_2 = new QSlider(tab_3);
        verticalSlider_2->setObjectName(QStringLiteral("verticalSlider_2"));
        verticalSlider_2->setGeometry(QRect(60, 20, 31, 160));
        verticalSlider_2->setOrientation(Qt::Vertical);
        verticalSlider_3 = new QSlider(tab_3);
        verticalSlider_3->setObjectName(QStringLiteral("verticalSlider_3"));
        verticalSlider_3->setGeometry(QRect(100, 20, 31, 160));
        verticalSlider_3->setOrientation(Qt::Vertical);
        verticalSlider_4 = new QSlider(tab_3);
        verticalSlider_4->setObjectName(QStringLiteral("verticalSlider_4"));
        verticalSlider_4->setGeometry(QRect(140, 20, 31, 160));
        verticalSlider_4->setOrientation(Qt::Vertical);
        verticalSlider_5 = new QSlider(tab_3);
        verticalSlider_5->setObjectName(QStringLiteral("verticalSlider_5"));
        verticalSlider_5->setGeometry(QRect(180, 20, 31, 160));
        verticalSlider_5->setOrientation(Qt::Vertical);
        verticalSlider_6 = new QSlider(tab_3);
        verticalSlider_6->setObjectName(QStringLiteral("verticalSlider_6"));
        verticalSlider_6->setGeometry(QRect(220, 20, 31, 160));
        verticalSlider_6->setOrientation(Qt::Vertical);
        verticalSlider_7 = new QSlider(tab_3);
        verticalSlider_7->setObjectName(QStringLiteral("verticalSlider_7"));
        verticalSlider_7->setGeometry(QRect(260, 20, 31, 160));
        verticalSlider_7->setOrientation(Qt::Vertical);
        verticalSlider_15 = new QSlider(tab_3);
        verticalSlider_15->setObjectName(QStringLiteral("verticalSlider_15"));
        verticalSlider_15->setGeometry(QRect(300, 20, 31, 160));
        verticalSlider_15->setOrientation(Qt::Vertical);
        verticalSlider_16 = new QSlider(tab_3);
        verticalSlider_16->setObjectName(QStringLiteral("verticalSlider_16"));
        verticalSlider_16->setGeometry(QRect(340, 20, 31, 160));
        verticalSlider_16->setOrientation(Qt::Vertical);
        verticalSlider_17 = new QSlider(tab_3);
        verticalSlider_17->setObjectName(QStringLiteral("verticalSlider_17"));
        verticalSlider_17->setGeometry(QRect(460, 20, 31, 160));
        verticalSlider_17->setOrientation(Qt::Vertical);
        verticalSlider_18 = new QSlider(tab_3);
        verticalSlider_18->setObjectName(QStringLiteral("verticalSlider_18"));
        verticalSlider_18->setGeometry(QRect(420, 20, 31, 160));
        verticalSlider_18->setOrientation(Qt::Vertical);
        verticalSlider_19 = new QSlider(tab_3);
        verticalSlider_19->setObjectName(QStringLiteral("verticalSlider_19"));
        verticalSlider_19->setGeometry(QRect(380, 20, 31, 160));
        verticalSlider_19->setOrientation(Qt::Vertical);
        verticalSlider_20 = new QSlider(tab_3);
        verticalSlider_20->setObjectName(QStringLiteral("verticalSlider_20"));
        verticalSlider_20->setGeometry(QRect(500, 20, 31, 160));
        verticalSlider_20->setOrientation(Qt::Vertical);
        verticalSlider_21 = new QSlider(tab_3);
        verticalSlider_21->setObjectName(QStringLiteral("verticalSlider_21"));
        verticalSlider_21->setGeometry(QRect(620, 20, 31, 160));
        verticalSlider_21->setOrientation(Qt::Vertical);
        verticalSlider_22 = new QSlider(tab_3);
        verticalSlider_22->setObjectName(QStringLiteral("verticalSlider_22"));
        verticalSlider_22->setGeometry(QRect(580, 20, 31, 160));
        verticalSlider_22->setOrientation(Qt::Vertical);
        verticalSlider_23 = new QSlider(tab_3);
        verticalSlider_23->setObjectName(QStringLiteral("verticalSlider_23"));
        verticalSlider_23->setGeometry(QRect(540, 20, 31, 160));
        verticalSlider_23->setOrientation(Qt::Vertical);
        verticalSlider_24 = new QSlider(tab_3);
        verticalSlider_24->setObjectName(QStringLiteral("verticalSlider_24"));
        verticalSlider_24->setGeometry(QRect(660, 20, 31, 160));
        verticalSlider_24->setOrientation(Qt::Vertical);
        verticalSlider_25 = new QSlider(tab_3);
        verticalSlider_25->setObjectName(QStringLiteral("verticalSlider_25"));
        verticalSlider_25->setGeometry(QRect(780, 20, 31, 160));
        verticalSlider_25->setOrientation(Qt::Vertical);
        verticalSlider_26 = new QSlider(tab_3);
        verticalSlider_26->setObjectName(QStringLiteral("verticalSlider_26"));
        verticalSlider_26->setGeometry(QRect(740, 20, 31, 160));
        verticalSlider_26->setOrientation(Qt::Vertical);
        verticalSlider_27 = new QSlider(tab_3);
        verticalSlider_27->setObjectName(QStringLiteral("verticalSlider_27"));
        verticalSlider_27->setGeometry(QRect(700, 20, 31, 160));
        verticalSlider_27->setOrientation(Qt::Vertical);
        verticalSlider_28 = new QSlider(tab_3);
        verticalSlider_28->setObjectName(QStringLiteral("verticalSlider_28"));
        verticalSlider_28->setGeometry(QRect(820, 20, 31, 160));
        verticalSlider_28->setOrientation(Qt::Vertical);
        verticalSlider_29 = new QSlider(tab_3);
        verticalSlider_29->setObjectName(QStringLiteral("verticalSlider_29"));
        verticalSlider_29->setGeometry(QRect(940, 20, 31, 160));
        verticalSlider_29->setOrientation(Qt::Vertical);
        verticalSlider_30 = new QSlider(tab_3);
        verticalSlider_30->setObjectName(QStringLiteral("verticalSlider_30"));
        verticalSlider_30->setGeometry(QRect(900, 20, 31, 160));
        verticalSlider_30->setOrientation(Qt::Vertical);
        verticalSlider_31 = new QSlider(tab_3);
        verticalSlider_31->setObjectName(QStringLiteral("verticalSlider_31"));
        verticalSlider_31->setGeometry(QRect(860, 20, 31, 160));
        verticalSlider_31->setOrientation(Qt::Vertical);
        verticalSlider_32 = new QSlider(tab_3);
        verticalSlider_32->setObjectName(QStringLiteral("verticalSlider_32"));
        verticalSlider_32->setGeometry(QRect(980, 20, 31, 160));
        verticalSlider_32->setOrientation(Qt::Vertical);
        lineEdit = new QLineEdit(tab_3);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(20, 190, 31, 21));
        lineEdit->setAlignment(Qt::AlignCenter);
        lineEdit_2 = new QLineEdit(tab_3);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(60, 190, 31, 21));
        lineEdit_2->setAlignment(Qt::AlignCenter);
        lineEdit_3 = new QLineEdit(tab_3);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(140, 190, 31, 21));
        lineEdit_3->setAlignment(Qt::AlignCenter);
        lineEdit_4 = new QLineEdit(tab_3);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(100, 190, 31, 21));
        lineEdit_4->setAlignment(Qt::AlignCenter);
        lineEdit_5 = new QLineEdit(tab_3);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(220, 190, 31, 21));
        lineEdit_5->setAlignment(Qt::AlignCenter);
        lineEdit_6 = new QLineEdit(tab_3);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(180, 190, 31, 21));
        lineEdit_6->setAlignment(Qt::AlignCenter);
        lineEdit_7 = new QLineEdit(tab_3);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(300, 190, 31, 21));
        lineEdit_7->setAlignment(Qt::AlignCenter);
        lineEdit_8 = new QLineEdit(tab_3);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(260, 190, 31, 21));
        lineEdit_8->setAlignment(Qt::AlignCenter);
        lineEdit_9 = new QLineEdit(tab_3);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(380, 190, 31, 21));
        lineEdit_9->setAlignment(Qt::AlignCenter);
        lineEdit_10 = new QLineEdit(tab_3);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(340, 190, 31, 21));
        lineEdit_10->setAlignment(Qt::AlignCenter);
        lineEdit_11 = new QLineEdit(tab_3);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(460, 190, 31, 21));
        lineEdit_11->setAlignment(Qt::AlignCenter);
        lineEdit_12 = new QLineEdit(tab_3);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(420, 190, 31, 21));
        lineEdit_12->setAlignment(Qt::AlignCenter);
        lineEdit_13 = new QLineEdit(tab_3);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(540, 190, 31, 21));
        lineEdit_13->setAlignment(Qt::AlignCenter);
        lineEdit_14 = new QLineEdit(tab_3);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(500, 190, 31, 21));
        lineEdit_14->setAlignment(Qt::AlignCenter);
        lineEdit_15 = new QLineEdit(tab_3);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(620, 190, 31, 21));
        lineEdit_15->setAlignment(Qt::AlignCenter);
        lineEdit_16 = new QLineEdit(tab_3);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(580, 190, 31, 21));
        lineEdit_16->setAlignment(Qt::AlignCenter);
        lineEdit_17 = new QLineEdit(tab_3);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(700, 190, 31, 21));
        lineEdit_17->setAlignment(Qt::AlignCenter);
        lineEdit_18 = new QLineEdit(tab_3);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(660, 190, 31, 21));
        lineEdit_18->setAlignment(Qt::AlignCenter);
        lineEdit_19 = new QLineEdit(tab_3);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(780, 190, 31, 21));
        lineEdit_19->setAlignment(Qt::AlignCenter);
        lineEdit_20 = new QLineEdit(tab_3);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(740, 190, 31, 21));
        lineEdit_20->setAlignment(Qt::AlignCenter);
        lineEdit_21 = new QLineEdit(tab_3);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(860, 190, 31, 21));
        lineEdit_21->setAlignment(Qt::AlignCenter);
        lineEdit_22 = new QLineEdit(tab_3);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(820, 190, 31, 21));
        lineEdit_22->setAlignment(Qt::AlignCenter);
        lineEdit_23 = new QLineEdit(tab_3);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(940, 190, 31, 21));
        lineEdit_23->setAlignment(Qt::AlignCenter);
        lineEdit_24 = new QLineEdit(tab_3);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(900, 190, 31, 21));
        lineEdit_24->setAlignment(Qt::AlignCenter);
        lineEdit_25 = new QLineEdit(tab_3);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(980, 190, 31, 21));
        lineEdit_25->setAlignment(Qt::AlignCenter);
        label = new QLabel(tab_3);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 0, 31, 16));
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(tab_3);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(60, 0, 31, 16));
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(tab_3);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(100, 0, 31, 16));
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(tab_3);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(180, 0, 31, 16));
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(tab_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(220, 0, 31, 16));
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(tab_3);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(140, 0, 31, 16));
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(300, 0, 31, 16));
        label_7->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(340, 0, 31, 16));
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(tab_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(260, 0, 31, 16));
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(420, 0, 31, 16));
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(tab_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(540, 0, 31, 16));
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(tab_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(500, 0, 31, 16));
        label_12->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(tab_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(460, 0, 31, 16));
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(tab_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(660, 0, 31, 16));
        label_14->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(tab_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(700, 0, 31, 16));
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(tab_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(620, 0, 31, 16));
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(tab_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(380, 0, 31, 16));
        label_17->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(tab_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(580, 0, 31, 16));
        label_18->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(tab_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(780, 0, 31, 16));
        label_19->setAlignment(Qt::AlignCenter);
        label_20 = new QLabel(tab_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(900, 0, 31, 16));
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(tab_3);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(860, 0, 31, 16));
        label_21->setAlignment(Qt::AlignCenter);
        label_22 = new QLabel(tab_3);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(820, 0, 31, 16));
        label_22->setAlignment(Qt::AlignCenter);
        label_25 = new QLabel(tab_3);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(980, 0, 31, 16));
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(tab_3);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(740, 0, 31, 16));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(tab_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(940, 0, 31, 16));
        label_27->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(tab_3);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 220, 991, 91));
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 30, 71, 20));
        pushButton_12 = new QPushButton(groupBox);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(1360, 120, 80, 20));
        pushButton_13 = new QPushButton(groupBox);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(730, 120, 80, 20));
        pushButton_14 = new QPushButton(groupBox);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(1000, 120, 80, 20));
        pushButton_15 = new QPushButton(groupBox);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(550, 120, 80, 20));
        pushButton_16 = new QPushButton(groupBox);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(640, 120, 80, 20));
        pushButton_17 = new QPushButton(groupBox);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(820, 120, 80, 20));
        pushButton_18 = new QPushButton(groupBox);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(460, 120, 80, 20));
        pushButton_19 = new QPushButton(groupBox);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(1270, 120, 80, 20));
        pushButton_20 = new QPushButton(groupBox);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(1090, 120, 80, 20));
        pushButton_21 = new QPushButton(groupBox);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(910, 120, 80, 20));
        pushButton_22 = new QPushButton(groupBox);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(1180, 120, 80, 20));
        pushButton_2 = new QPushButton(groupBox);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(100, 30, 71, 20));
        pushButton_3 = new QPushButton(groupBox);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(190, 30, 71, 20));
        pushButton_4 = new QPushButton(groupBox);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(280, 30, 71, 20));
        pushButton_5 = new QPushButton(groupBox);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(370, 30, 71, 20));
        pushButton_6 = new QPushButton(groupBox);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(460, 30, 71, 20));
        pushButton_7 = new QPushButton(groupBox);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(550, 30, 71, 20));
        pushButton_8 = new QPushButton(groupBox);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(640, 30, 71, 20));
        pushButton_9 = new QPushButton(groupBox);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(730, 30, 71, 20));
        pushButton_10 = new QPushButton(groupBox);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(820, 30, 71, 20));
        pushButton_11 = new QPushButton(groupBox);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(910, 30, 71, 20));
        pushButton_23 = new QPushButton(groupBox);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(640, 60, 71, 20));
        pushButton_24 = new QPushButton(groupBox);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(460, 60, 71, 20));
        pushButton_25 = new QPushButton(groupBox);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(910, 60, 71, 20));
        pushButton_26 = new QPushButton(groupBox);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(190, 60, 71, 20));
        pushButton_27 = new QPushButton(groupBox);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(280, 60, 71, 20));
        pushButton_28 = new QPushButton(groupBox);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(370, 60, 71, 20));
        pushButton_29 = new QPushButton(groupBox);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(820, 60, 71, 20));
        pushButton_30 = new QPushButton(groupBox);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(100, 60, 71, 20));
        pushButton_31 = new QPushButton(groupBox);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(10, 60, 71, 20));
        pushButton_32 = new QPushButton(groupBox);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(550, 60, 71, 20));
        pushButton_33 = new QPushButton(groupBox);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(730, 60, 71, 20));
        tabWidget->addTab(tab_3, QString());
        statusBar = new QLabel(centralwidget);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        statusBar->setGeometry(QRect(10, 490, 331, 16));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1060, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        readPlainTextEdit->setPlainText(QApplication::translate("MainWindow", "\346\216\245\346\224\266\346\265\213\350\257\225\357\274\201\357\274\201\357\274\201", Q_NULLPTR));
        writeTextEdit->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\345\217\221\351\200\201\346\265\213\350\257\225\357\274\201\357\274\201\357\274\201</p></body></html>", Q_NULLPTR));
        chartPushButton->setText(QApplication::translate("MainWindow", "\345\233\276\350\241\250", Q_NULLPTR));
        actionConfigure->setText(QApplication::translate("MainWindow", "\351\205\215\347\275\256", Q_NULLPTR));
        actionConnect->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\243", Q_NULLPTR));
        actionDisconnect->setText(QApplication::translate("MainWindow", "\346\226\255\345\274\200", Q_NULLPTR));
        actionSend->setText(QApplication::translate("MainWindow", "\345\217\221\351\200\201", Q_NULLPTR));
        actionClear->setText(QApplication::translate("MainWindow", "\346\270\205\351\231\244\346\216\245\346\224\266", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", " \344\270\262\345\217\243\350\260\203\350\257\225\345\212\251\346\211\213", Q_NULLPTR));
        ValidRadioButton->setText(QApplication::translate("MainWindow", "\346\225\210\351\252\214", Q_NULLPTR));
        stopBtn->setText(QApplication::translate("MainWindow", "\345\274\200\345\247\213", Q_NULLPTR));
        YcheckBox->setText(QApplication::translate("MainWindow", "Y\350\275\264", Q_NULLPTR));
        paramLabel->setText(QApplication::translate("MainWindow", "\345\217\202\346\225\260", Q_NULLPTR));
        XcheckBox->setText(QApplication::translate("MainWindow", "X\350\275\264", Q_NULLPTR));
        autoCheckBox->setText(QApplication::translate("MainWindow", "\350\207\252\345\212\250", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "\345\233\276\350\241\250", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "11", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "14", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "13", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "12", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "17", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "18", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "16", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "10", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "15", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "20", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "23", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "22", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "21", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "25", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "19", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "24", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", " \351\241\265", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "1-25", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_21->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("MainWindow", "PushButton", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "26-50", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("MainWindow", "51-75", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "76-100", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("MainWindow", "101-125", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("MainWindow", "126-150", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("MainWindow", "151-175", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("MainWindow", "176-200", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "201-225", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("MainWindow", "226-250", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "251-275", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("MainWindow", "451-475", Q_NULLPTR));
        pushButton_24->setText(QApplication::translate("MainWindow", "401-425", Q_NULLPTR));
        pushButton_25->setText(QApplication::translate("MainWindow", " \345\244\215\344\275\215", Q_NULLPTR));
        pushButton_26->setText(QApplication::translate("MainWindow", "326-350", Q_NULLPTR));
        pushButton_27->setText(QApplication::translate("MainWindow", "351-375", Q_NULLPTR));
        pushButton_28->setText(QApplication::translate("MainWindow", "376-400", Q_NULLPTR));
        pushButton_29->setText(QApplication::translate("MainWindow", "501-512", Q_NULLPTR));
        pushButton_30->setText(QApplication::translate("MainWindow", "301-325", Q_NULLPTR));
        pushButton_31->setText(QApplication::translate("MainWindow", "276-300", Q_NULLPTR));
        pushButton_32->setText(QApplication::translate("MainWindow", "426-450", Q_NULLPTR));
        pushButton_33->setText(QApplication::translate("MainWindow", "476-500", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "DMX", Q_NULLPTR));
        statusBar->setText(QApplication::translate("MainWindow", " \347\212\266\346\200\201\346\240\217", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
